site_name: Help Center
site_url: http://127.0.0.1:8000/
site_description: "Glean Help Center"
repo_url: https://github.com/nathancatania/Glean-Docs
repo_name: GitHub
edit_uri: blob/main/docs/
copyright: "&copy; 2023, Glean Technologies, Inc."

    

theme:
  language: en
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  logo: assets/images/banner-logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: glean
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  
  features:
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCY0JDJWRBXrR0m1SqWPVB9A
      name: Glean on YouTube
    
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/glean
      name: Glean on X (formerly Twitter)

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gleanwork/about/
      name: Glean on LinkedIn
  alternate:
    - name: English
      link: /
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - awesome-pages
  - table-reader
#  - tags # Disabling tags until they can be repositioned
  - social:
      cards_layout_options:
        cards_layout: default
        background_color: #343CED # Change background color
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: Japanese
          build: true


extra_css:
  - stylesheets/extra.css

# Site navigation
# nav:
#   - Home: index.md
#   - Getting Started:
#       - Welcome: getting-started/welcome.md
#       - Access the Admin UI: getting-started/adminui.md
#       - Setup Single Sign-On (SSO): getting-started/sso.md
#       - Sync People Data: getting-started/people-data.md
#       - Connect Datasources: getting-started/datasources.md
#       - Setup Glean Assistant: getting-started/assistant.md
#   - Assistant:
#       - assistant/*
