site_name: Help Center
site_url: "https://help.glean.com"
site_description: "Glean Help Center"
repo_url: https://github.com/nathancatania/glean-docs
repo_name: glean/glean-docs
edit_uri: edit/main/docs/
copyright: "&copy; 2023, Glean Technologies, Inc."

announcement:
  message: "Testing!"
  status: "info"

theme:
  language: en
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  logo: assets/images/banner-logo.svg
  icon:
    repo: material/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: glean
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - announce.dismiss
    - content.action.edit
    - content.action.view

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCY0JDJWRBXrR0m1SqWPVB9A
      name: Glean on YouTube
    
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/glean
      name: Glean on X (formerly Twitter)

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gleanwork/about/
      name: Glean on LinkedIn
  alternate:
    - name: English
      link: /
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - meta
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - awesome-pages
  - table-reader
  - search
#  - tags # Disabling tags until they can be repositioned
  - social:
      cards_layout_options:
        cards_layout: default
        background_color: "#343CED" # Change background color
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: Japanese
          build: true
          nav_translations:
            Home: ホーム
            Getting Started: はじめに
            Architecture: アーキテクチャ
            Search: 検索
            Assistant: アシスタント
            Platform: プラットフォーム
            Administration: 管理
            API: API
            Support Portal: サポートポータル
            Welcome: ようこそ
            Access the Admin UI: 管理者UIにアクセス
            Setup Single Sign-On (SSO): シングルサインオン（SSO）のセットアップ
            Sync People Data: 人データの同期
            Connect Datasources: データソースの接続
            Setup Glean Assistant: Gleanアシスタントのセットアップ
            Post-Setup: セットアップ後
            Customize your Workspace: ワークスペースのカスタマイズ
            Deploy the Glean Extension: Glean拡張機能のデプロイ
            Self Hosted: セルフホスト
            Glean Deployment Options: Gleanデプロイオプション
            Deploying Glean in GCP: GCPでのGleanのデプロイ
            Deploying Glean in AWS: AWSでのGleanのデプロイ
  - blog:
      enabled: false
      # Disabled blog due to current incompatibility with mkdocs-static-i18n: https://github.com/ultrabug/mkdocs-static-i18n/pull/268#issuecomment-1779215704
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: long
      post_url_format: "{slug}"
      draft_if_future_date: true
      draft_on_serve: true
      blog_toc: true
  - git-revision-date-localized:
      type: date
  - git-committers:
      repository: nathancatania/glean-docs
      branch: main
      enabled: !ENV [CI, false]


extra_css:
  - stylesheets/extra.css

# Site navigation
# nav:
#   - Home: index.md
#   - Getting Started:
#       - Welcome: getting-started/welcome.md
#       - Access the Admin UI: getting-started/adminui.md
#       - Setup Single Sign-On (SSO): getting-started/sso.md
#       - Sync People Data: getting-started/people-data.md
#       - Connect Datasources: getting-started/datasources.md
#       - Setup Glean Assistant: getting-started/assistant.md
#   - Assistant:
#       - assistant/*


